// axi4_seq_item — AXI4 burst descriptor: stimulus generated by sequences,
// and the item published by the monitor after observing the bus.
//
// `included from axi4_pkg.sv. Must come first — every other file in this
// directory references axi4_seq_item.

class axi4_seq_item extends uvm_sequence_item;

    // Stimulus
    rand bit          is_write;
    rand bit [31:0]   addr;
    rand int unsigned beats;         // 1..256
    bit [7:0]         data[$];       // bytes, filled by the sequence

    // Observed response
    bit [1:0]         resp;

    `uvm_object_utils(axi4_seq_item)

    // Aligned to the bus width and inside the testbench's reduced 64 KB
    // MEM_DEPTH.
    // TODO(#12): relax for narrow_test and error_test.
    constraint c_addr  { addr[2:0] == 3'b000; addr < 32'h0001_0000; }
    constraint c_beats { beats inside {[1:16]}; }

    function new(string name = "axi4_seq_item");
        super.new(name);
    endfunction

    function string convert2string();
        return $sformatf("%s addr=0x%08h beats=%0d bytes=%0d resp=%0d",
                         is_write ? "WRITE" : "READ",
                         addr, beats, data.size(), resp);
    endfunction

endclass
