// C side of the DPI-C contract: implements the functions imported by
// axi_ram_dpi.sv and owns the model generated by Verilator.

#include "axi_ram_dpi.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <memory>
#include <string>
#include <vector>

#include "Vaxi_ram_dpi.h"
#include "svdpi.h"
#include "verilated.h"

namespace {

// Verilator registers the scope as "<model name>.<module name>", where the model
// name defaults to "TOP". Composed at runtime so we do not depend on that
// default.
constexpr const char* SV_MODULE = "axi_ram_dpi";

std::unique_ptr<Vaxi_ram_dpi> g_top;

// Exchange buffer shared with the BFM. Only one request is ever in flight, so a
// single buffer shared between reads and writes is enough.
std::vector<uint8_t> g_buffer(AXI_DPI_MAX_BYTES, 0);

bool     g_clk_high = false;
uint64_t g_ticks    = 0;

void require_init(const char* who) {
    if (!g_top) {
        std::fprintf(stderr,
                     "axi_ram_dpi: %s called before axi_dpi::init()\n", who);
        std::abort();
    }
}

}  // namespace

// ── Functions imported by the SystemVerilog side ─────────────────────────────

extern "C" unsigned char axi_dpi_get_wbyte(int idx) {
    if (idx < 0 || static_cast<size_t>(idx) >= g_buffer.size()) {
        std::fprintf(stderr, "axi_dpi_get_wbyte: idx %d out of range\n", idx);
        std::abort();
    }
    return g_buffer[static_cast<size_t>(idx)];
}

extern "C" void axi_dpi_put_rbyte(int idx, unsigned char val) {
    if (idx < 0 || static_cast<size_t>(idx) >= g_buffer.size()) {
        std::fprintf(stderr, "axi_dpi_put_rbyte: idx %d out of range\n", idx);
        std::abort();
    }
    g_buffer[static_cast<size_t>(idx)] = val;
}

// ── API consumed by the RamAxi SC_MODULE ─────────────────────────────────────

namespace axi_dpi {

void init() {
    if (g_top) return;

    g_top = std::make_unique<Vaxi_ram_dpi>();

    // Without this the first call to an exported DPI function aborts with
    // "scope wasn't set". Verilator requires the SV scope to be set explicitly
    // before invoking exports from C++.
    const std::string scope_name =
        std::string(g_top->name()) + "." + SV_MODULE;
    svScope scope = svGetScopeFromName(scope_name.c_str());
    if (!scope) {
        std::fprintf(stderr, "axi_ram_dpi: SV scope '%s' does not exist\n",
                     scope_name.c_str());
        std::abort();
    }
    svSetScope(scope);

    // The BFM leaves reset with the FSM in S_IDLE and ack_seq == req_seq == 0,
    // i.e. reporting "done". A few cycles with aresetn low are enough.
    g_top->aresetn = 0;
    g_top->aclk    = 0;
    for (int i = 0; i < 8; ++i) {
        g_top->aclk = !g_top->aclk;
        g_top->eval();
    }
    g_top->aresetn = 1;
    g_clk_high     = false;
    g_top->eval();
}

void tick() {
    require_init("tick");
    g_clk_high  = !g_clk_high;
    g_top->aclk = g_clk_high ? 1 : 0;
    g_top->eval();
    ++g_ticks;
}

void shutdown() {
    if (!g_top) return;
    g_top->final();
    g_top.reset();
}

void load_write_buffer(const unsigned char* src, int len) {
    if (len < 0 || static_cast<size_t>(len) > g_buffer.size()) {
        std::fprintf(stderr, "load_write_buffer: len %d out of range\n", len);
        std::abort();
    }
    std::copy(src, src + len, g_buffer.begin());
}

void store_read_buffer(unsigned char* dst, int len) {
    if (len < 0 || static_cast<size_t>(len) > g_buffer.size()) {
        std::fprintf(stderr, "store_read_buffer: len %d out of range\n", len);
        std::abort();
    }
    std::copy(g_buffer.begin(), g_buffer.begin() + len, dst);
}

uint64_t tick_count() {
    return g_ticks;
}

}  // namespace axi_dpi
